### ISSUE TITLE
Openrouteservice.org API

### ISSUE THREAD

**Issue by onplot** [gis-support/qgis-location-lab-plugin#6]
Any chance you could integrate this FREE! api - [https://openrouteservice.org/plans/]

?

Max

**Comment by michaldrozdz** [comment]
Yes, it is! We are updateing the plugin this week and we will consider openrouteservice very seriously. Thanks for hint!

**Comment by onplot** [comment]
You might also want to look at HERE as they have changed the api key and Skobbler doesn't even send out site registration emails anymore so not sure you can get an api from them.  Is it the api that sets the limit of 5 points or something you guys set?
